apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: ironclouder
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rodrigolsoria/ironclouders_final_project:Back
          ports:
            - containerPort: 8080  
