apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: ironclouder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest  
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: admin123
          - name: POSTGRES_DB
            value: basic3tier
        ports:
        - containerPort: 5432 
