apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
    namespace: ironclouder
    labels:
        app: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            name: frontend
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: rodrigolsoria/ironclouders_final_project:Front
                  ports:
                      - containerPort: 80
