apiVersion: v1
kind: Service
metadata:
    name: loadbalancer-service
    namespace: ironclouder
spec:
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 80
    selector:
        app: frontend
