- name: Installing Grafana
  hosts: all
  become: yes
  tasks:
  - name: Create a volume
    docker_volume:
      name: Grafana_volume

  - name: Create Grafana container
    docker_container:
      name: Grafana
      restart_policy: always
      image: grafana/grafana-oss
      volumes:
        - Grafana_volume:/var/lib/grafana
      ports: 
        - "3000:3000"
